### ISSUE TITLE
App crashed once the credential offer is send from the cloud agent.

### ISSUE THREAD

**Issue by darkchylde** [decentralised-dataexchange/aries-mobileagent-android#1]
### Stacktrace

```
2020-12-05 18:34:56.015 6273-6273/io.igrant.mobileagent E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.igrant.mobileagent, PID: 6273
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:501)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: org.json.JSONException: Value null at records of type org.json.JSONObject$1 cannot be converted to JSONArray
        at org.json.JSON.typeMismatch(JSON.java:101)
        at org.json.JSONObject.getJSONArray(JSONObject.java:598)
        at io.igrant.mobileagent.activty.InitializeActivity.searchDidKey(InitializeActivity.kt:939)
        at io.igrant.mobileagent.activty.InitializeActivity.unPackOfferCredential(InitializeActivity.kt:904)
        at io.igrant.mobileagent.activty.InitializeActivity.unPackPollMessage(InitializeActivity.kt:531)
        at io.igrant.mobileagent.activty.InitializeActivity.access$unPackPollMessage(InitializeActivity.kt:90)
        at io.igrant.mobileagent.activty.InitializeActivity$pollMessagesInThread$1$run$1.onResponse(InitializeActivity.kt:439)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:81)
        at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$3wC8FyV4pyjrzrYL5U0mlYiviZw.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by darkchylde** [comment]
@josmilan Will test this.
