### ISSUE TITLE
App crash when clicking on the data exchange notification.

### ISSUE THREAD

**Issue by darkchylde** [decentralised-dataexchange/aries-mobileagent-android#50]
App crashed when clicking on the data exchange notification.

### Stacktrace

```
2020-12-23 11:08:11.506 30584-30794/io.igrant.mobileagent E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: io.igrant.mobileagent, PID: 30584
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.util.concurrent.ExecutionException: org.hyperledger.indy.sdk.pool.InvalidPoolException: The pool is closed or invalid and cannot be used.
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:361)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1923)
        at io.igrant.mobileagent.indy.PoolUtils.createAndOpenPoolLedger(PoolUtils.java:76)
        at io.igrant.mobileagent.tasks.PoolTask.doInBackground(PoolTask.kt:14)
        at io.igrant.mobileagent.tasks.PoolTask.doInBackground(PoolTask.kt:10)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: org.hyperledger.indy.sdk.pool.InvalidPoolException: The pool is closed or invalid and cannot be used.
        at org.hyperledger.indy.sdk.IndyJava$API.checkResult(IndyJava.java:92)
        at org.hyperledger.indy.sdk.pool.Pool.access$100(Pool.java:20)
        at org.hyperledger.indy.sdk.pool.Pool$1.callback(Pool.java:52)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:520)
        at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:551)
2020-12-23 11:08:11.523 30584-30794/io.igrant.mobileagent I/Process: Sending signal. PID: 30584 SIG: 9

```

**Comment by darkchylde** [comment]
@josmilan For the current sprint, we don't need the notification to be clickable.
